config/routes.rb
Gulch2::Application.routes.draw do
  resources :tarifftools
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  match '/signup',  to: 'users#new',          via: 'get'
  match '/signin',  to: 'sessions#new',       via: 'get' 
  match '/signout', to: 'sessions#destroy',   via: 'delete'
  match '/input',   to: 'tariff_tools#input', via: 'get'
  match '/tool',    to: 'tariff_tools#tool',  via: 'get'
  
  

  

end

app/controllers/tariff_tools_controller.rb
class TariffToolsController < ApplicationController

	def index
	end

	def create
		@zip = params[:tariff_input][:zip_code]
		#session[:demand_in_kW] = params[:session][:demand_in_kW]
		#session[:usage_in_kWh] = params[:session][:usage_in_kWh]
		#session[:bill_date] = params[:session][:bill_date]
		#session[:phases] = params[:session][:phases]

		redirect_to tool_path
	end

end

app/helpers/tariff_tools_helper.rb
module TariffToolsHelper
end

app/views/tariff_tools/home.html.erb
<h1>Bill Comparison Demo</h1>

<p>
	This is the page where the Bill Comparison Demo will reside
</p>

app/views/tariff_tools/index.html.erb
<h1>Input Zip Code</h1>

<div class="row">
	<div class="span6 offset3">
		
		<%=form_for(@tariff_tools, url: tariff_tools_path) do |f| %>

			<br> <!-- enters a blank line, ie: line break -->
			<%= f.label :zip_code %>
			<%= f.text_field :current_zip, {:value => '07004'} %>

			<br> <!-- enters a blank line, ie: line break -->
			<%= f.label :demand_kW %>
			<%= f.text_field :current_demand, {:value => '100'} %>

			<br> <!-- enters a blank line, ie: line break -->
			<%= f.label :usage_kWh %>
			<%= f.text_field :current_usage, {:value => '10000'} %>

			<br> <!-- enters a blank line, ie: line break -->
			<%= f.label :bill_date %>
			<%= f.text_field :current_date, {:value => '10/1/2013'} %>

			<br> <!-- enters a blank line, ie: line break -->
			<%= f.label :phases %>
			<%= f.text_field :current_phases, {:value => '3-phase'} %>

			<br> <!-- enters a blank line, ie: line break -->
			<%= f.submit "Submit", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/tariff_tools/input.html.erb
<h1>Input Zip Code</h1>

<div class="row">
	<div class="span6 offset3">
		
		<%=form_for(:session, url: sessions_path) do |f| %>

			<br> <!-- enters a blank line, ie: line break -->
			<%= f.label :zip_code %>
			<%= f.text_field :zip_code, {:value => '07004'} %>

			<br> <!-- enters a blank line, ie: line break -->
			<%= f.label :demand_in_kW %>
			<%= f.text_field :demand_in_kW, {:value => '100'} %>

			<br> <!-- enters a blank line, ie: line break -->
			<%= f.label :usage_in_kWh %>
			<%= f.text_field :usage_in_kWh, {:value => '10000'} %>

			<br> <!-- enters a blank line, ie: line break -->
			<%= f.label :bill_date %>
			<%= f.text_field :bill_date, {:value => '10/1/2013'} %>

			<br> <!-- enters a blank line, ie: line break -->
			<%= f.label :phases %>
			<%= f.text_field :phases, {:value => '3-phase'} %>

			<br> <!-- enters a blank line, ie: line break -->
			<%= f.submit "Submit", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/tariff_tools/test.html.erb
<h1>This page displays the value from the input form</h1>

<p>
	<%  @form_value = session[:form_value2] %>
	<%= @form_value %>
</p>

app/views/tariff_tools/tool.html.erb
<h1>Bill Comparison (Demo)</h1>

<p> <!-- gets all the data needed to display the bill -->
	<% @zip = session[:zip_code] %>
	<% @demand = session[:demand_in_kW] %>
	<% @usage = session[:usage_in_kWh] %>
	<% @date = session[:bill_date] %>
	<% @phases = session[:phases] %>

	<% @utility = TariffUtility.utility(@zip) %> 
	<% @territory = TariffTerritory.territory(@zip) %>
	<% @season = TariffSeason.season(@date, @zip) %> 
	<% @tou = TariffTou.tou(@date, @zip) %>
	<% @meter_read = TariffMeterRead.meter_read(@date, @zip) %>
	<% @billing_class = TariffBillingClass.billing_class(@zip, @demand, @usage, @phases) %>
	<% @tariffs = TariffTariff.tariffs(@billing_class) %>
	<% @line_items = TariffLineItems.line_items(@tariffs, @date, @season) %>
	<% @bill_groups = TariffBillGroup.bill_groups(@billing_class) %>	
	
	<!-- shows the utility and billing period -->
	<%= @date %>
	<br> <!-- enters a blank line, ie: line break -->
	<%= @utility.utility_name %>
	<br> <!-- enters a blank line, ie: line break -->
	<strong> Billing Period: <%= @meter_read["start_date"] %> to <%= @meter_read["end_date"] %> </strong>
	<br> <!-- enters a blank line, ie: line break -->

</p>

<p> <!-- this area shows the header information for the bill -->
	kWh used = <%= @usage %>
	<br> <!-- enters a blank line, ie: line break -->
	Billed Load in kW = <%= @demand %>
	<br> <!-- enters a blank line, ie: line break -->
	<br> <!-- enters a blank line, ie: line break -->
	Rate: <%= @billing_class[0].billing_class_name %>
	<br> <!-- enters a blank line, ie: line break -->

	<!-- sorts the line items by bill group -->
	<% @line_items.sort_by{ |i| i.bill_group_order} %>
	<% @bill_groups.sort_by{ |i| i.bill_group_order} %>

</p>

<% @bill_total = 0 %>
<% @bill_groups.each do |j| %>
	<!-- shows the name of the section of the bill -->
	<strong><%= j.bill_group_name %></strong>
	<br> <!-- enters a blank line, ie: line break -->
	
	<table> <!-- to test my understanding of tables -->
		<% @bill_group_total = 0 %>
		<% @line_items.each do |i| %>
			<% if j.id == i.tariff_bill_group_id %>
				<tr>
					<td> <%= i.line_item_name %> </td> <!-- name -->
					<% case i.line_item_type %>
					<% when '$/month' %>
						<td> </td>	<!-- value -->
						<td> </td> 	<!-- value label -->
						<td> </td>	<!-- math symbol -->
						<td> </td> 	<!-- rate -->
						<td> 
							<% @bill_group_total += i.line_item_rate %>
							<%= number_to_currency(i.line_item_rate) %> <!-- total -->
						</td> 

					<% when '$/kW' %>
						<td> <%= @demand %> </td>	<!-- value -->
						<td> kW </td> 	<!-- value label -->
						<td> x </td>	<!-- math symbol -->
						<td> <%= number_to_currency(i.line_item_rate, precision: 3) %> </td> 	<!-- rate -->
						<td> 
							<% @bill_group_total += (i.line_item_rate * @demand.to_f) %>
							<%= number_to_currency(i.line_item_rate * @demand.to_f) %> <!-- total -->
						</td> 
					<% when '$/kWh' %>
						<td> <%= @usage %> </td>	<!-- value -->
						<td> kWh </td> 	<!-- value label -->
						<td> x </td>	<!-- math symbol -->
						<td> <%= number_to_currency(i.line_item_rate, precision: 6) %> </td> 	<!-- rate -->
						<td> 
							<% @bill_group_total += (i.line_item_rate * @usage.to_f) %>
							<%= number_to_currency(i.line_item_rate * @usage.to_f) %> <!-- total -->
						</td> 
					<% when 'Stepped' %>
						<% @stepped_rates = TariffSteppedRates.stepped_rates(i.id) %>
						<% @stepped_rates.each do |k| %>
							<% case k.stepped_rates_unit %>
							<% when 'kW' %>
								<% if @demand.to_f > k.stepped_rates_start %>
									<tr>
										<td> </td>
										<td> 
											<% if k.stepped_rates_end.blank? %> 
												<% @temp_value = (@demand.to_f - k.start) %>
											<% else %>
												<% if @demand.to_f > k.stepped_rates_end %>
													<% @temp_value = (k.end - k.start) %>
												<% else %>
													<% @temp_value = (@demand.to_f - k.stepped_rates_start) %>
												<% end %>
											<% end %>
											<%= @temp_value %> <!-- value -->
										</td>	
										<td> kW </td> 	<!-- value label -->
										<td> x </td>	<!-- math symbol -->
										<td> <%= number_to_currency(k.line_item_rate, precision: 6) %> </td> 	<!-- rate -->
										<td> 
											<% @bill_group_total += (k.line_item_rate * @temp_value) %>
											<%= number_to_currency(k.line_item_rate * @temp_value) %> <!-- total -->
										</td>
									</tr> 
								<% end %>
							<% when 'kWh' %>
								<% if @usage.to_f > k.stepped_rates_start %>
									<tr>
										<td> </td>
										<td> 
											<% if k.stepped_rates_end.blank? %> 
												<% @temp_value = (@usage.to_f - k.stepped_rates_start) %>
											<% else %>
												<% if @usage.to_f > k.stepped_rates_end %>
													<% @temp_value = (k.stepped_rates_end - k.stepped_rates_start) %>
												<% else %>
													<% @temp_value = (@usage.to_f - k.stepped_rates_start) %>
												<% end %>
											<% end %>
											<%= @temp_value %> <!-- value -->
										</td>	
										<td> kWh </td> 	<!-- value label -->
										<td> x </td>	<!-- math symbol -->
										<td> <%= number_to_currency(k.stepped_rates_rate, precision: 6) %> </td> 	<!-- rate -->
										<td> 
											<% @bill_group_total += (k.stepped_rates_rate * @temp_value) %>
											<%= number_to_currency(k.stepped_rates_rate * @temp_value) %> <!-- total -->
										</td>
									</tr> 
								<% end %>
							<% else %>
								This is going to be a problem <!-- flags an issue with the data in the database -->
							<% end %>
						<% end %>
					<% else %>
						<td> <%= i.line_item_type %> </td>

					<% end %>
				</tr>
			<% end %>
		<% end %>
	</table>
	<!-- determines the total for that section of the bill -->
	
	&nbsp &nbsp &nbsp &nbsp &nbsp Total for <%= j.bill_group_name %> = <%= number_to_currency(@bill_group_total) %>
	<% @bill_total += @bill_group_total %>
	<br> <!-- enters a blank line, ie: line break -->
<% end %>
<h3>
	Total Bill = <%= number_to_currency(@bill_total) %>
</h3>